/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.JmfUsuarios;
import tools.Util;
import dao.ProdutosDAO;
import dao.UsuariosDAO;

/**
 *
 * @author admin
 */
public class JDlgUsuarios extends javax.swing.JDialog {
private boolean incluir;
    /**
     * Creates new form jDlgClientes
     * @param parent
     * @param modal
     */
    public JDlgUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro do Usuarios");
        setLocationRelativeTo(null);
        Util.habilitar(false,jTxtCodigo, jTxtNome, jTxtApelido,
                jFmtCpf, jFmtDataNascimentoUsuarios, jPwdSenha, jCboNivel, jCboAtivo,
                jBtnConfirmarUsuarios, jBtnCancelarUsuarios);
        

    }
public JmfUsuarios viewBean(){
    JmfUsuarios jmfUsuarios = new JmfUsuarios();
    
    
    int codigo = Util.strToInt(jTxtCodigo.getText());
    jmfUsuarios.setJmfIdusuarios(codigo);
    jmfUsuarios.setJmfNome(jTxtNome.getText());
    jmfUsuarios.setJmfApelido(jTxtApelido.getText());
    jmfUsuarios.setJmfCpf(jFmtCpf.toString());
    jmfUsuarios.setJmfSenha(jPwdSenha.toString());
    jmfUsuarios.setJmfNivel(jCboNivel.getSelectedIndex());
    jFmtDataNascimentoUsuarios.setText(Util.dateToStr(jmfUsuarios.getJmfDatanascimento()));
    if (jCboAtivo.isSelected()== true){
            jmfUsuarios.setJmfAtivo("S")
                    ;
        } else {
            jmfUsuarios.setJmfAtivo("N");
        }
  

    return jmfUsuarios;
}
    public void beanView(JmfUsuarios jmfUsuarios) {
    jTxtCodigo.setText(Util.intToStr(jmfUsuarios.getJmfIdusuarios()));
    jTxtNome.setText(jmfUsuarios.getJmfNome());
    jTxtApelido.setText(jmfUsuarios.getJmfApelido());
    jFmtCpf.setText(jmfUsuarios.getJmfCpf());
    jPwdSenha.setText(jmfUsuarios.getJmfSenha());
    jCboNivel.setSelectedIndex(jmfUsuarios.getJmfNivel());
    jFmtDataNascimentoUsuarios.setText(Util.dateToStr(jmfUsuarios.getJmfDatanascimento()));
    if ("S".equals(jmfUsuarios.getJmfAtivo())) {
        jCboAtivo.setSelected(true);
    } else {
        jCboAtivo.setSelected(false);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCboAtivo = new javax.swing.JCheckBox();
        jTxtCodigo = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();
        jTxtApelido = new javax.swing.JTextField();
        jFmtCpf = new javax.swing.JFormattedTextField();
        jFmtDataNascimentoUsuarios = new javax.swing.JFormattedTextField();
        jPwdSenha = new javax.swing.JPasswordField();
        jCboNivel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jBtnIncluirUsuarios = new javax.swing.JButton();
        jBtnAlterarUsuarios = new javax.swing.JButton();
        jBtnExcluirUsuarios = new javax.swing.JButton();
        jBtnConfirmarUsuarios = new javax.swing.JButton();
        jBtnCancelarUsuarios = new javax.swing.JButton();
        jBtnPesquisarUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Usuario");

        jLabel2.setText("Nome");

        jLabel3.setText("Apelido");

        jLabel4.setText("CPF");

        jLabel5.setText("Data de Nascimento");

        jLabel6.setText("Senha");

        jCboAtivo.setText("Ativo");
        jCboAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboAtivoActionPerformed(evt);
            }
        });

        jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoActionPerformed(evt);
            }
        });

        jCboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario Comum", "Convidado", "Outro" }));

        jLabel8.setText("Nivel");

        jBtnIncluirUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluirUsuarios.setText("Incluir");
        jBtnIncluirUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirUsuariosActionPerformed(evt);
            }
        });

        jBtnAlterarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterarUsuarios.setText("Alterar");
        jBtnAlterarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarUsuariosActionPerformed(evt);
            }
        });

        jBtnExcluirUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluirUsuarios.setText("Excluir");
        jBtnExcluirUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirUsuariosActionPerformed(evt);
            }
        });

        jBtnConfirmarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnConfirmarUsuarios.setText("Confirmar");
        jBtnConfirmarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarUsuariosActionPerformed(evt);
            }
        });

        jBtnCancelarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnCancelarUsuarios.setText("Cancelar");
        jBtnCancelarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarUsuariosActionPerformed(evt);
            }
        });

        jBtnPesquisarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisarUsuarios.setText("Pesquisar");
        jBtnPesquisarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtCodigo)
                    .addComponent(jTxtNome)
                    .addComponent(jTxtApelido)
                    .addComponent(jFmtCpf)
                    .addComponent(jFmtDataNascimentoUsuarios)
                    .addComponent(jPwdSenha)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jCboAtivo)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnIncluirUsuarios)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnAlterarUsuarios)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnExcluirUsuarios)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jBtnConfirmarUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnCancelarUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnPesquisarUsuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtDataNascimentoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addComponent(jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboAtivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluirUsuarios)
                    .addComponent(jBtnAlterarUsuarios)
                    .addComponent(jBtnExcluirUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmarUsuarios)
                    .addComponent(jBtnCancelarUsuarios)
                    .addComponent(jBtnPesquisarUsuarios))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboAtivoActionPerformed

    private void jBtnConfirmarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarUsuariosActionPerformed
        // TODO add your handling code here:
          UsuariosDAO usuariosDAO = new UsuariosDAO();
        if (incluir == true){
         usuariosDAO.insert(viewBean());
        }else {
        usuariosDAO.update(viewBean());
        }
       Util.habilitar(false,jTxtCodigo, jTxtApelido, jTxtNome, jFmtCpf, jFmtDataNascimentoUsuarios,
                jPwdSenha, jCboAtivo, jBtnConfirmarUsuarios, jBtnCancelarUsuarios);
        Util.habilitar(true, jBtnIncluirUsuarios, jBtnAlterarUsuarios, jBtnExcluirUsuarios, jBtnPesquisarUsuarios);

        
        

    }//GEN-LAST:event_jBtnConfirmarUsuariosActionPerformed

    private void jBtnIncluirUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirUsuariosActionPerformed
      Util.habilitar(true, jTxtCodigo, jTxtApelido, jTxtNome, jFmtCpf, jFmtDataNascimentoUsuarios,
                jPwdSenha, jCboAtivo, jCboNivel, jBtnConfirmarUsuarios, jBtnCancelarUsuarios);
        Util.habilitar(false, jBtnIncluirUsuarios, jBtnAlterarUsuarios, jBtnExcluirUsuarios, jBtnPesquisarUsuarios);
        Util.Limpar(jTxtCodigo, jTxtApelido, jTxtNome, jFmtCpf, jFmtDataNascimentoUsuarios,
                jPwdSenha, jCboAtivo, jCboNivel);
         jTxtCodigo.grabFocus();
        incluir = true;
    }//GEN-LAST:event_jBtnIncluirUsuariosActionPerformed

    private void jBtnAlterarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarUsuariosActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false,jTxtCodigo, jTxtApelido, jTxtNome, jCboNivel, jFmtCpf, jFmtDataNascimentoUsuarios,
                jPwdSenha, jCboAtivo, jBtnConfirmarUsuarios, jBtnCancelarUsuarios);
        Util.habilitar(true, jBtnIncluirUsuarios, jBtnAlterarUsuarios, jBtnExcluirUsuarios, jBtnPesquisarUsuarios);
          Util.Limpar(jTxtCodigo, jTxtApelido, jTxtNome, jFmtCpf, jFmtDataNascimentoUsuarios,
                jPwdSenha, jCboAtivo, jCboNivel);
        jTxtNome.grabFocus();
        incluir = false;

    }//GEN-LAST:event_jBtnAlterarUsuariosActionPerformed

    private void jBtnExcluirUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirUsuariosActionPerformed
        // TODO add your handling code here:
          if (Util.perguntar("Deseja Excluir?") == true) {
            UsuariosDAO usuariosDAO = new UsuariosDAO();
            usuariosDAO.delete(viewBean());

        }
        Util.Limpar(jTxtCodigo, jTxtApelido, jTxtNome, jFmtCpf, jFmtDataNascimentoUsuarios,
                jPwdSenha, jCboAtivo, jCboNivel);  
         
    }//GEN-LAST:event_jBtnExcluirUsuariosActionPerformed

    private void jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoActionPerformed

    private void jBtnCancelarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarUsuariosActionPerformed
        // TODO add your handling code here:
    Util.habilitar(true,jTxtCodigo, jTxtApelido, jTxtNome, jFmtCpf, jCboNivel, jFmtDataNascimentoUsuarios,
                jPwdSenha, jCboAtivo, jBtnConfirmarUsuarios, jBtnCancelarUsuarios);
        Util.habilitar(false, jBtnIncluirUsuarios, jBtnAlterarUsuarios, jBtnExcluirUsuarios, jBtnPesquisarUsuarios);

    }//GEN-LAST:event_jBtnCancelarUsuariosActionPerformed

    private void jBtnPesquisarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarUsuariosActionPerformed
        // TODO add your handling code here:
         JDlgUsuariosPesquisar jDlgUsuariosPesquisar = new JDlgUsuariosPesquisar(null, true);     
        jDlgUsuariosPesquisar.setTelaAnterior(this);
        jDlgUsuariosPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            JDlgUsuarios dialog = new JDlgUsuarios(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterarUsuarios;
    private javax.swing.JButton jBtnCancelarUsuarios;
    private javax.swing.JButton jBtnConfirmarUsuarios;
    private javax.swing.JButton jBtnExcluirUsuarios;
    private javax.swing.JButton jBtnIncluirUsuarios;
    private javax.swing.JButton jBtnPesquisarUsuarios;
    private javax.swing.JCheckBox jCboAtivo;
    private javax.swing.JComboBox<String> jCboNivel;
    private javax.swing.JFormattedTextField jFmtCpf;
    private javax.swing.JFormattedTextField jFmtDataNascimentoUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPwdSenha;
    private javax.swing.JTextField jTxtApelido;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtNome;
    // End of variables declaration//GEN-END:variables
}
