/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.JmfVendedores;
import dao.VendedoresDAO;
import tools.Util;

/**
 *
 * @author admin
 */
public class JDlgVendedor extends javax.swing.JDialog {
     private boolean incluir;

    /**
     * Creates new form jDlgClientes
     * @param parent
     * @param modal
     */
    public JDlgVendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro do Vendedor");
        setLocationRelativeTo(null);
        
        Util.habilitar(false,jTxtNomeVendedor, jTxtApelidoVendedor, jTxtCidadeVendedor,
                jTxtCodigoVendedor, jTxtEmailVendedor, jTxtEnderecoVendedor, jTxtEstadoVendedor,
                jChbAtivoVendedor, jFmtCelularVendedor, jFmtCpfVendedor, jFmtDataNascimentoVendedor,
                jFmtrgVendedor, jBtnConfirmar, jBntCancelar);
        

    }
     public JmfVendedores viewBean(){
    JmfVendedores jmfVendedores = new JmfVendedores();
    
    
    int codigo = Util.strToInt(jTxtCodigoVendedor.getText());
    jmfVendedores.setJmfIdVendedor(codigo);
    jmfVendedores.setJmfNome(jTxtNomeVendedor.getText());
    jmfVendedores.setJmfApelido(jTxtApelidoVendedor.getText());
    jmfVendedores.setJmfCpf(jFmtCpfVendedor.toString());
    jmfVendedores.setJmfRg(jFmtrgVendedor.toString());
    jmfVendedores.setJmfEndereco(jTxtEnderecoVendedor.getText());
    jmfVendedores.setJmfCidade(jTxtCidadeVendedor.getText());
    jmfVendedores.setJmfEstado(jTxtEstadoVendedor.getText());
    jmfVendedores.setJmfEmail(jTxtEmailVendedor.getText());
    jmfVendedores.setJmfCelular(jFmtCelularVendedor.getText());
    jFmtDataNascimentoVendedor.setText(Util.dateToStr(jmfVendedores.getJmfDataNascimento()));
    if (jChbAtivoVendedor.isSelected()== true){
            jmfVendedores.setJmfAtivo("S")
                    ;
        } else {
            jmfVendedores.setJmfAtivo("N");
        }
  

    return jmfVendedores;
}
    public void beanView(JmfVendedores jmfVendedores) {
    jTxtCodigoVendedor.setText(Util.intToStr(jmfVendedores.getJmfIdVendedor()));
    jTxtNomeVendedor.setText(jmfVendedores.getJmfNome());
    jTxtApelidoVendedor.setText(jmfVendedores.getJmfApelido());
    jFmtCpfVendedor.setText(jmfVendedores.getJmfCpf());
    jFmtrgVendedor.setText(jmfVendedores.getJmfRg());
    jTxtEnderecoVendedor.setText(jmfVendedores.getJmfEndereco());
    jTxtCidadeVendedor.setText(jmfVendedores.getJmfCidade());
    jTxtEstadoVendedor.setText(jmfVendedores.getJmfEstado());
    jTxtEmailVendedor.setText(jmfVendedores.getJmfEmail());
    jFmtCelularVendedor.setText(jmfVendedores.getJmfCelular());
    jFmtDataNascimentoVendedor.setText(Util.dateToStr(jmfVendedores.getJmfDataNascimento()));

    if ("S".equals(jmfVendedores.getJmfAtivo())) {
        jChbAtivoVendedor.setSelected(true);
    } else {
        jChbAtivoVendedor.setSelected(false);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTxtCodigoVendedor = new javax.swing.JTextField();
        jTxtNomeVendedor = new javax.swing.JTextField();
        jTxtApelidoVendedor = new javax.swing.JTextField();
        jFmtCpfVendedor = new javax.swing.JFormattedTextField();
        jFmtrgVendedor = new javax.swing.JFormattedTextField();
        jTxtEnderecoVendedor = new javax.swing.JTextField();
        jTxtCidadeVendedor = new javax.swing.JTextField();
        jTxtEstadoVendedor = new javax.swing.JTextField();
        jTxtEmailVendedor = new javax.swing.JTextField();
        jFmtCelularVendedor = new javax.swing.JFormattedTextField();
        jFmtDataNascimentoVendedor = new javax.swing.JFormattedTextField();
        jChbAtivoVendedor = new javax.swing.JCheckBox();
        jBntIncluir = new javax.swing.JButton();
        jBntAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBntCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo do Vendedor");

        jLabel2.setText("Nome");

        jLabel3.setText("Apelido");

        jLabel4.setText("CPF");

        jLabel5.setText("RG");

        jLabel7.setText("Endereço");

        jLabel8.setText("Cidade");

        jLabel9.setText("Estado");

        jLabel10.setText("Email");

        jLabel12.setText("Celular");

        jLabel14.setText("Data de Nascimento");

        jChbAtivoVendedor.setText("Ativo ");

        jBntIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBntIncluir.setText("Incluir");
        jBntIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntIncluirActionPerformed(evt);
            }
        });

        jBntAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBntAlterar.setText("Alterar");
        jBntAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBntCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBntCancelar.setText("Cancelar");
        jBntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFmtDataNascimentoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jChbAtivoVendedor)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBntIncluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBntAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jBntCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnPesquisar))
                    .addComponent(jTxtCodigoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxtApelidoVendedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                        .addComponent(jFmtrgVendedor, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jTxtEnderecoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCidadeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jFmtCpfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEstadoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEmailVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtCelularVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtApelidoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtCpfVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(jFmtrgVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(2, 2, 2)
                .addComponent(jTxtEnderecoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(jTxtCidadeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addComponent(jTxtEstadoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtEmailVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtCelularVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtDataNascimentoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChbAtivoVendedor)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBntIncluir)
                    .addComponent(jBntAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBntCancelar)
                    .addComponent(jBtnPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBntIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true,jTxtNomeVendedor, jTxtApelidoVendedor, jTxtCidadeVendedor, jTxtCodigoVendedor, jTxtEmailVendedor,
                jTxtEnderecoVendedor, jTxtEstadoVendedor,
                jChbAtivoVendedor, jFmtCelularVendedor, jFmtCpfVendedor, jFmtDataNascimentoVendedor,
                jFmtrgVendedor, jBtnConfirmar, jBntCancelar);
        Util.habilitar(false, jBntIncluir, jBntAlterar, jBtnExcluir, jBtnPesquisar);
        Util.Limpar(jTxtNomeVendedor, jTxtApelidoVendedor, jTxtCidadeVendedor, jTxtCodigoVendedor, jTxtEmailVendedor,
                jTxtEnderecoVendedor, jTxtEstadoVendedor,
                jChbAtivoVendedor, jFmtCelularVendedor, jFmtCpfVendedor, jFmtDataNascimentoVendedor); 
         jTxtCodigoVendedor.grabFocus();
        incluir = true;

    }//GEN-LAST:event_jBntIncluirActionPerformed

    private void jBntAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntAlterarActionPerformed
        // TODO add your handling code here:
         Util.habilitar(false,jTxtNomeVendedor, jTxtApelidoVendedor, jTxtCidadeVendedor, jTxtCodigoVendedor, jTxtEmailVendedor,
                jTxtEnderecoVendedor, jTxtEstadoVendedor,
                jChbAtivoVendedor, jFmtCelularVendedor, jFmtCpfVendedor, jFmtDataNascimentoVendedor,
                jFmtrgVendedor, jBtnConfirmar, jBntCancelar);
        Util.habilitar(true, jBntIncluir, jBntAlterar, jBtnExcluir, jBtnPesquisar);
         jTxtNomeVendedor.grabFocus();
        incluir = false;


    }//GEN-LAST:event_jBntAlterarActionPerformed

    private void jBntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntCancelarActionPerformed
Util.habilitar(true, jTxtNomeVendedor, jTxtApelidoVendedor, jTxtCidadeVendedor, jTxtCodigoVendedor, jTxtEmailVendedor,
                jTxtEnderecoVendedor, jTxtEstadoVendedor,
                jChbAtivoVendedor, jFmtCelularVendedor, jFmtCpfVendedor, jFmtDataNascimentoVendedor,
                jFmtrgVendedor);
        Util.habilitar(false, jBntIncluir, jBtnConfirmar, jBtnExcluir, jBtnPesquisar);
      
        
    }//GEN-LAST:event_jBntCancelarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
         
        VendedoresDAO vendedoresDAO = new VendedoresDAO();
        if (incluir == true){
         vendedoresDAO.insert(viewBean());
        }else {
        vendedoresDAO.update(viewBean());
        }
        Util.habilitar(false, jTxtNomeVendedor, jTxtApelidoVendedor, jTxtCidadeVendedor, jTxtCodigoVendedor, jTxtEmailVendedor,
                jTxtEnderecoVendedor, jTxtEstadoVendedor,
                jChbAtivoVendedor, jFmtCelularVendedor, jFmtCpfVendedor, jFmtDataNascimentoVendedor,
                jFmtrgVendedor, jBtnConfirmar, jBntCancelar);
        Util.habilitar(true, jBntIncluir, jBntAlterar, jBtnExcluir, jBtnPesquisar);
       
     
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
       if (Util.perguntar("Deseja Excluir?") == true) {
            VendedoresDAO vendedoresDAO = new VendedoresDAO();
            vendedoresDAO.delete(viewBean());

        }
      
        Util.Limpar( jTxtNomeVendedor, jTxtApelidoVendedor, jTxtCidadeVendedor, jTxtCodigoVendedor, jTxtEmailVendedor,
                jTxtEnderecoVendedor, jTxtEstadoVendedor,
                jChbAtivoVendedor, jFmtCelularVendedor, jFmtCpfVendedor, jFmtDataNascimentoVendedor,
                jFmtrgVendedor);
      
      
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
    JDlgVendedoresPesquisar jDlgVendedoresPesquisar = new JDlgVendedoresPesquisar(null, true);     
        jDlgVendedoresPesquisar.setTelaAnterior(this);
        jDlgVendedoresPesquisar.setVisible(true);

    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            JDlgVendedor dialog = new JDlgVendedor(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBntAlterar;
    private javax.swing.JButton jBntCancelar;
    private javax.swing.JButton jBntIncluir;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JCheckBox jChbAtivoVendedor;
    private javax.swing.JFormattedTextField jFmtCelularVendedor;
    private javax.swing.JFormattedTextField jFmtCpfVendedor;
    private javax.swing.JFormattedTextField jFmtDataNascimentoVendedor;
    private javax.swing.JFormattedTextField jFmtrgVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtApelidoVendedor;
    private javax.swing.JTextField jTxtCidadeVendedor;
    private javax.swing.JTextField jTxtCodigoVendedor;
    private javax.swing.JTextField jTxtEmailVendedor;
    private javax.swing.JTextField jTxtEnderecoVendedor;
    private javax.swing.JTextField jTxtEstadoVendedor;
    private javax.swing.JTextField jTxtNomeVendedor;
    // End of variables declaration//GEN-END:variables
}
