/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.JDlgClientes;
import view.JDlgProdutos;
import view.JDlgUsuarios;
import view.JDlgVendedor;

/**
 *
 * @author u08317670147
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Sistema Freire");
        setExtendedState(JFrmPrincipal.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnCadastro = new javax.swing.JMenu();
        jMnUsuarios = new javax.swing.JMenuItem();
        jMnClientes = new javax.swing.JMenuItem();
        jMnVendedor = new javax.swing.JMenuItem();
        jMnProdutos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnSair = new javax.swing.JMenuItem();
        jMnMovimento = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gravar.png"))); // NOI18N
        jMnCadastro.setText("Cadastro");

        jMnUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMnUsuarios.setText("Usuarios");
        jMnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnUsuariosActionPerformed(evt);
            }
        });
        jMnCadastro.add(jMnUsuarios);

        jMnClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMnClientes.setText("Clientes");
        jMnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnClientesActionPerformed(evt);
            }
        });
        jMnCadastro.add(jMnClientes);

        jMnVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedores.png"))); // NOI18N
        jMnVendedor.setText("Vendedor");
        jMnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnVendedorActionPerformed(evt);
            }
        });
        jMnCadastro.add(jMnVendedor);

        jMnProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto.png"))); // NOI18N
        jMnProdutos.setText("Produtos");
        jMnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnProdutosActionPerformed(evt);
            }
        });
        jMnCadastro.add(jMnProdutos);
        jMnCadastro.add(jSeparator1);

        jMnSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit_1_1.png"))); // NOI18N
        jMnSair.setText("Sair");
        jMnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnSairActionPerformed(evt);
            }
        });
        jMnCadastro.add(jMnSair);

        jMenuBar1.add(jMnCadastro);

        jMnMovimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedores.png"))); // NOI18N
        jMnMovimento.setText("Movimento");
        jMenuBar1.add(jMnMovimento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgUsuarios jDlgUsuarios = new JDlgUsuarios(null, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnUsuariosActionPerformed

    private void jMnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnClientesActionPerformed
        // TODO add your handling code here:
        JDlgClientes jDlgClientes = new JDlgClientes(null, true);
        jDlgClientes.setVisible(true);
    }//GEN-LAST:event_jMnClientesActionPerformed

    private void jMnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnVendedorActionPerformed
        // TODO add your handling code here:
        JDlgVendedor jDlgVendedor = new JDlgVendedor(null, true);
        jDlgVendedor.setVisible(true);
    }//GEN-LAST:event_jMnVendedorActionPerformed

    private void jMnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnProdutosActionPerformed
        // TODO add your handling code here:
        JDlgProdutos jDlgProdutos = new JDlgProdutos(null, true);
        jDlgProdutos.setVisible(true);
    }//GEN-LAST:event_jMnProdutosActionPerformed

    private void jMnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnCadastro;
    private javax.swing.JMenuItem jMnClientes;
    private javax.swing.JMenu jMnMovimento;
    private javax.swing.JMenuItem jMnProdutos;
    private javax.swing.JMenuItem jMnSair;
    private javax.swing.JMenuItem jMnUsuarios;
    private javax.swing.JMenuItem jMnVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
