package bean;
// Generated 29/09/2025 10:38:31 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;

import javax.persistence.Id;

import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JmfClientes generated by hbm2java
 */
@Entity
@Table(name="jmf_clientes"
    ,catalog="db_julia_freire"
)
public class JmfClientes  implements java.io.Serializable {


     private int jmfIdCliente;
     private String jmfNome;
     private String jmfCpf;
     private String jmfRg;
     private String jmfSexo;
     private Date jmfDataNascimento;
     private String jmfEmail;
     private String jmfEndereco;
     private String jmfTelefone;
     private String jmfCelular;
     private Date jmfDataCadastro;
     private String jmfAtivo;
     private Date jmfDataUltimaCompra;
     private BigDecimal jmfLimiteCredito;
     private String jmfEstadoCivil;
   

    public JmfClientes() {
    }

	
    public JmfClientes(int jmfIdCliente) {
        this.jmfIdCliente = jmfIdCliente;
    }
    public JmfClientes(int jmfIdCliente, String jmfNome, String jmfCpf, String jmfRg, String jmfSexo, Date jmfDataNascimento, String jmfEmail, String jmfEndereco, String jmfTelefone, String jmfCelular, Date jmfDataCadastro, String jmfAtivo, Date jmfDataUltimaCompra, BigDecimal jmfLimiteCredito, String jmfEstadoCivil) {
       this.jmfIdCliente = jmfIdCliente;
       this.jmfNome = jmfNome;
       this.jmfCpf = jmfCpf;
       this.jmfRg = jmfRg;
       this.jmfSexo = jmfSexo;
       this.jmfDataNascimento = jmfDataNascimento;
       this.jmfEmail = jmfEmail;
       this.jmfEndereco = jmfEndereco;
       this.jmfTelefone = jmfTelefone;
       this.jmfCelular = jmfCelular;
       this.jmfDataCadastro = jmfDataCadastro;
       this.jmfAtivo = jmfAtivo;
       this.jmfDataUltimaCompra = jmfDataUltimaCompra;
       this.jmfLimiteCredito = jmfLimiteCredito;
       this.jmfEstadoCivil = jmfEstadoCivil;
       
    }
   
     @Id 

    
    @Column(name="jmf_IdCliente", unique=true, nullable=false)
    public int getJmfIdCliente() {
        return this.jmfIdCliente;
    }
    
    public void setJmfIdCliente(int jmfIdCliente) {
        this.jmfIdCliente = jmfIdCliente;
    }

    
    @Column(name="jmf_nome", length=100)
    public String getJmfNome() {
        return this.jmfNome;
    }
    
    public void setJmfNome(String jmfNome) {
        this.jmfNome = jmfNome;
    }

    
    @Column(name="jmf_cpf", length=11)
    public String getJmfCpf() {
        return this.jmfCpf;
    }
    
    public void setJmfCpf(String jmfCpf) {
        this.jmfCpf = jmfCpf;
    }

    
    @Column(name="jmf_rg", length=10)
    public String getJmfRg() {
        return this.jmfRg;
    }
    
    public void setJmfRg(String jmfRg) {
        this.jmfRg = jmfRg;
    }

    
    @Column(name="jmf_sexo", length=10)
    public String getJmfSexo() {
        return this.jmfSexo;
    }
    
    public void setJmfSexo(String jmfSexo) {
        this.jmfSexo = jmfSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jmf_dataNascimento", length=10)
    public Date getJmfDataNascimento() {
        return this.jmfDataNascimento;
    }
    
    public void setJmfDataNascimento(Date jmfDataNascimento) {
        this.jmfDataNascimento = jmfDataNascimento;
    }

    
    @Column(name="jmf_email", length=60)
    public String getJmfEmail() {
        return this.jmfEmail;
    }
    
    public void setJmfEmail(String jmfEmail) {
        this.jmfEmail = jmfEmail;
    }

    
    @Column(name="jmf_endereco", length=150)
    public String getJmfEndereco() {
        return this.jmfEndereco;
    }
    
    public void setJmfEndereco(String jmfEndereco) {
        this.jmfEndereco = jmfEndereco;
    }

    
    @Column(name="jmf_telefone", length=15)
    public String getJmfTelefone() {
        return this.jmfTelefone;
    }
    
    public void setJmfTelefone(String jmfTelefone) {
        this.jmfTelefone = jmfTelefone;
    }

    
    @Column(name="jmf_celular", length=15)
    public String getJmfCelular() {
        return this.jmfCelular;
    }
    
    public void setJmfCelular(String jmfCelular) {
        this.jmfCelular = jmfCelular;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jmf_dataCadastro", length=10)
    public Date getJmfDataCadastro() {
        return this.jmfDataCadastro;
    }
    
    public void setJmfDataCadastro(Date jmfDataCadastro) {
        this.jmfDataCadastro = jmfDataCadastro;
    }

    
    @Column(name="jmf_ativo", length=1)
    public String getJmfAtivo() {
        return this.jmfAtivo;
    }
    
    public void setJmfAtivo(String jmfAtivo) {
        this.jmfAtivo = jmfAtivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jmf_dataUltimaCompra", length=10)
    public Date getJmfDataUltimaCompra() {
        return this.jmfDataUltimaCompra;
    }
    
    public void setJmfDataUltimaCompra(Date jmfDataUltimaCompra) {
        this.jmfDataUltimaCompra = jmfDataUltimaCompra;
    }

    
    @Column(name="jmf_limiteCredito", precision=10)
    public BigDecimal getJmfLimiteCredito() {
        return this.jmfLimiteCredito;
    }
    
    public void setJmfLimiteCredito(BigDecimal jmfLimiteCredito) {
        this.jmfLimiteCredito = jmfLimiteCredito;
    }

    
    @Column(name="jmf_estadoCivil", length=11)
    public String getJmfEstadoCivil() {
        return this.jmfEstadoCivil;
    }
    
    public void setJmfEstadoCivil(String jmfEstadoCivil) {
        this.jmfEstadoCivil = jmfEstadoCivil;
    }





}


