package bean;
// Generated 29/09/2025 10:38:31 by Hibernate Tools 4.3.1



import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JmfProdutos generated by hbm2java
 */
@Entity
@Table(name="jmf_produtos"
    ,catalog="db_julia_freire"
)
public class JmfProdutos  implements java.io.Serializable {


     private int jmfId;
     private String jmfNome;
     private String jmfDescricao;
     private String jmfCategoria;
     private String jmfFornecedor;
     private Double jmfPreco;
     private String jmfProduto;
     private String jmfAtivo;


    public JmfProdutos() {
    }

	
    public JmfProdutos(int jmfId) {
        this.jmfId = jmfId;
    }
    public JmfProdutos(int jmfId, String jmfNome, String jmfDescricao, String jmfCategoria, String jmfFornecedor, Double jmfPreco, String jmfProduto, String jmfAtivo) {
       this.jmfId = jmfId;
       this.jmfNome = jmfNome;
       this.jmfDescricao = jmfDescricao;
       this.jmfCategoria = jmfCategoria;
       this.jmfFornecedor = jmfFornecedor;
       this.jmfPreco = jmfPreco;
       this.jmfProduto = jmfProduto;
       this.jmfAtivo = jmfAtivo;
      
    }
   
     @Id 

    
    @Column(name="jmf_id", unique=true, nullable=false)
    public int getJmfId() {
        return this.jmfId;
    }
    
    public void setJmfId(int jmfId) {
        this.jmfId = jmfId;
    }

    
    @Column(name="jmf_nome", length=50)
    public String getJmfNome() {
        return this.jmfNome;
    }
    
    public void setJmfNome(String jmfNome) {
        this.jmfNome = jmfNome;
    }

    
    @Column(name="jmf_descricao")
    public String getJmfDescricao() {
        return this.jmfDescricao;
    }
    
    public void setJmfDescricao(String jmfDescricao) {
        this.jmfDescricao = jmfDescricao;
    }

    
    @Column(name="jmf_categoria", length=100)
    public String getJmfCategoria() {
        return this.jmfCategoria;
    }
    
    public void setJmfCategoria(String jmfCategoria) {
        this.jmfCategoria = jmfCategoria;
    }

    
    @Column(name="jmf_fornecedor", length=100)
    public String getJmfFornecedor() {
        return this.jmfFornecedor;
    }
    
    public void setJmfFornecedor(String jmfFornecedor) {
        this.jmfFornecedor = jmfFornecedor;
    }

    
    @Column(name="jmf_preco", precision=22, scale=0)
    public Double getJmfPreco() {
        return this.jmfPreco;
    }
    
    public void setJmfPreco(Double jmfPreco) {
        this.jmfPreco = jmfPreco;
    }

    
    @Column(name="jmf_produto", length=50)
    public String getJmfProduto() {
        return this.jmfProduto;
    }
    
    public void setJmfProduto(String jmfProduto) {
        this.jmfProduto = jmfProduto;
    }

    
    @Column(name="jmf_ativo", length=1)
    public String getJmfAtivo() {
        return this.jmfAtivo;
    }
    
    public void setJmfAtivo(String jmfAtivo) {
        this.jmfAtivo = jmfAtivo;
    }





}


