package bean;
// Generated 29/09/2025 10:38:31 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JmfUsuarios generated by hbm2java
 */
@Entity
@Table(name="jmf_usuarios"
    ,catalog="db_julia_freire"
)
public class JmfUsuarios  implements java.io.Serializable {


     private int jmfIdusuarios;
     private String jmfNome;
     private String jmfApelido;
     private String jmfCpf;
     private Date jmfDatanascimento;
     private String jmfSenha;
     private Integer jmfNivel;
     private String jmfAtivo;
     

    public JmfUsuarios() {
    }

	
    public JmfUsuarios(int jmfIdusuarios) {
        this.jmfIdusuarios = jmfIdusuarios;
    }
    public JmfUsuarios(int jmfIdusuarios, String jmfNome, String jmfApelido, String jmfCpf, Date jmfDatanascimento, String jmfSenha, Integer jmfNivel, String jmfAtivo) {
       this.jmfIdusuarios = jmfIdusuarios;
       this.jmfNome = jmfNome;
       this.jmfApelido = jmfApelido;
       this.jmfCpf = jmfCpf;
       this.jmfDatanascimento = jmfDatanascimento;
       this.jmfSenha = jmfSenha;
       this.jmfNivel = jmfNivel;
       this.jmfAtivo = jmfAtivo;
    }
   
     @Id 

    
    @Column(name="jmf_idusuarios", unique=true, nullable=false)
    public int getJmfIdusuarios() {
        return this.jmfIdusuarios;
    }
    
    public void setJmfIdusuarios(int jmfIdusuarios) {
        this.jmfIdusuarios = jmfIdusuarios;
    }

    
    @Column(name="jmf_nome", length=100)
    public String getJmfNome() {
        return this.jmfNome;
    }
    
    public void setJmfNome(String jmfNome) {
        this.jmfNome = jmfNome;
    }

    
    @Column(name="jmf_apelido", length=50)
    public String getJmfApelido() {
        return this.jmfApelido;
    }
    
    public void setJmfApelido(String jmfApelido) {
        this.jmfApelido = jmfApelido;
    }

    
    @Column(name="jmf_cpf", length=14)
    public String getJmfCpf() {
        return this.jmfCpf;
    }
    
    public void setJmfCpf(String jmfCpf) {
        this.jmfCpf = jmfCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jmf_datanascimento", length=10)
    public Date getJmfDatanascimento() {
        return this.jmfDatanascimento;
    }
    
    public void setJmfDatanascimento(Date jmfDatanascimento) {
        this.jmfDatanascimento = jmfDatanascimento;
    }

    
    @Column(name="jmf_senha", length=20)
    public String getJmfSenha() {
        return this.jmfSenha;
    }
    
    public void setJmfSenha(String jmfSenha) {
        this.jmfSenha = jmfSenha;
    }

    
    @Column(name="jmf_nivel")
    public Integer getJmfNivel() {
        return this.jmfNivel;
    }
    
    public void setJmfNivel(Integer jmfNivel) {
        this.jmfNivel = jmfNivel;
    }

    
    @Column(name="jmf_ativo", length=1)
    public String getJmfAtivo() {
        return this.jmfAtivo;
    }
    
    public void setJmfAtivo(String jmfAtivo) {
        this.jmfAtivo = jmfAtivo;
    }




}


