package bean;
// Generated 29/09/2025 10:38:31 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JmfVendas generated by hbm2java
 */
@Entity
@Table(name="jmf_vendas"
    ,catalog="db_julia_freire"
)
public class JmfVendas  implements java.io.Serializable {


     private int jmfIdVendas;
     private JmfClientes jmfClientes;
     private JmfUsuarios jmfUsuarios;
     private Date jmfDataVendas;
     private BigDecimal jmfTotal;
   

    public JmfVendas() {
    }

	
    public JmfVendas(int jmfIdVendas) {
        this.jmfIdVendas = jmfIdVendas;
    }
    public JmfVendas(int jmfIdVendas, JmfClientes jmfClientes, JmfUsuarios jmfUsuarios, Date jmfDataVendas, BigDecimal jmfTotal) {
       this.jmfIdVendas = jmfIdVendas;
       this.jmfClientes = jmfClientes;
       this.jmfUsuarios = jmfUsuarios;
       this.jmfDataVendas = jmfDataVendas;
       this.jmfTotal = jmfTotal;
      
    }
   
     @Id 

    
    @Column(name="jmf_idVendas", unique=true, nullable=false)
    public int getJmfIdVendas() {
        return this.jmfIdVendas;
    }
    
    public void setJmfIdVendas(int jmfIdVendas) {
        this.jmfIdVendas = jmfIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jmf_cliente")
    public JmfClientes getJmfClientes() {
        return this.jmfClientes;
    }
    
    public void setJmfClientes(JmfClientes jmfClientes) {
        this.jmfClientes = jmfClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jmf_usuario")
    public JmfUsuarios getJmfUsuarios() {
        return this.jmfUsuarios;
    }
    
    public void setJmfUsuarios(JmfUsuarios jmfUsuarios) {
        this.jmfUsuarios = jmfUsuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jmf_dataVendas", length=10)
    public Date getJmfDataVendas() {
        return this.jmfDataVendas;
    }
    
    public void setJmfDataVendas(Date jmfDataVendas) {
        this.jmfDataVendas = jmfDataVendas;
    }

    
    @Column(name="jmf_total", precision=10)
    public BigDecimal getJmfTotal() {
        return this.jmfTotal;
    }
    
    public void setJmfTotal(BigDecimal jmfTotal) {
        this.jmfTotal = jmfTotal;
    }




}


