package bean;
// Generated 29/09/2025 10:38:31 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JmfVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="jmf_vendas_produtos"
    ,catalog="db_julia_freire"
)
public class JmfVendasProdutos  implements java.io.Serializable {


     private int jmfIdVendasProdutos;
     private JmfProdutos jmfProdutos;
     private JmfVendas jmfVendas;
     private Integer jmfQuantidade;
     private BigDecimal jmfValorUnitario;

    public JmfVendasProdutos() {
    }

	
    public JmfVendasProdutos(int jmfIdVendasProdutos) {
        this.jmfIdVendasProdutos = jmfIdVendasProdutos;
    }
    public JmfVendasProdutos(int jmfIdVendasProdutos, JmfProdutos jmfProdutos, JmfVendas jmfVendas, Integer jmfQuantidade, BigDecimal jmfValorUnitario) {
       this.jmfIdVendasProdutos = jmfIdVendasProdutos;
       this.jmfProdutos = jmfProdutos;
       this.jmfVendas = jmfVendas;
       this.jmfQuantidade = jmfQuantidade;
       this.jmfValorUnitario = jmfValorUnitario;
    }
   
     @Id 

    
    @Column(name="jmf_idVendas_produtos", unique=true, nullable=false)
    public int getJmfIdVendasProdutos() {
        return this.jmfIdVendasProdutos;
    }
    
    public void setJmfIdVendasProdutos(int jmfIdVendasProdutos) {
        this.jmfIdVendasProdutos = jmfIdVendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jmf_produtos")
    public JmfProdutos getJmfProdutos() {
        return this.jmfProdutos;
    }
    
    public void setJmfProdutos(JmfProdutos jmfProdutos) {
        this.jmfProdutos = jmfProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jmf_vendas")
    public JmfVendas getJmfVendas() {
        return this.jmfVendas;
    }
    
    public void setJmfVendas(JmfVendas jmfVendas) {
        this.jmfVendas = jmfVendas;
    }

    
    @Column(name="jmf_quantidade")
    public Integer getJmfQuantidade() {
        return this.jmfQuantidade;
    }
    
    public void setJmfQuantidade(Integer jmfQuantidade) {
        this.jmfQuantidade = jmfQuantidade;
    }

    
    @Column(name="jmf_valor_unitario", precision=10)
    public BigDecimal getJmfValorUnitario() {
        return this.jmfValorUnitario;
    }
    
    public void setJmfValorUnitario(BigDecimal jmfValorUnitario) {
        this.jmfValorUnitario = jmfValorUnitario;
    }




}


