package bean;
// Generated 29/09/2025 10:38:31 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JmfVendedores generated by hbm2java
 */
@Entity
@Table(name="jmf_vendedores"
    ,catalog="db_julia_freire"
)
public class JmfVendedores  implements java.io.Serializable {


     private int jmfIdVendedor;
     private String jmfNome;
     private String jmfApelido;
     private String jmfCpf;
     private String jmfRg;
     private Date jmfDataNascimento;
     private String jmfCelular;
     private String jmfEmail;
     private String jmfEndereco;
     private String jmfCidade;
     private String jmfEstado;
     private String jmfAtivo;

    public JmfVendedores() {
    }

	
    public JmfVendedores(int jmfIdVendedor) {
        this.jmfIdVendedor = jmfIdVendedor;
    }
    public JmfVendedores(int jmfIdVendedor, String jmfNome, String jmfApelido, String jmfCpf, String jmfRg, Date jmfDataNascimento, String jmfCelular, String jmfEmail, String jmfEndereco, String jmfCidade, String jmfEstado, String jmfAtivo) {
       this.jmfIdVendedor = jmfIdVendedor;
       this.jmfNome = jmfNome;
       this.jmfApelido = jmfApelido;
       this.jmfCpf = jmfCpf;
       this.jmfRg = jmfRg;
       this.jmfDataNascimento = jmfDataNascimento;
       this.jmfCelular = jmfCelular;
       this.jmfEmail = jmfEmail;
       this.jmfEndereco = jmfEndereco;
       this.jmfCidade = jmfCidade;
       this.jmfEstado = jmfEstado;
       this.jmfAtivo = jmfAtivo;
    }
   
     @Id 

    
    @Column(name="jmf_id_vendedor", unique=true, nullable=false)
    public int getJmfIdVendedor() {
        return this.jmfIdVendedor;
    }
    
    public void setJmfIdVendedor(int jmfIdVendedor) {
        this.jmfIdVendedor = jmfIdVendedor;
    }

    
    @Column(name="jmf_nome", length=50)
    public String getJmfNome() {
        return this.jmfNome;
    }
    
    public void setJmfNome(String jmfNome) {
        this.jmfNome = jmfNome;
    }

    
    @Column(name="jmf_apelido", length=30)
    public String getJmfApelido() {
        return this.jmfApelido;
    }
    
    public void setJmfApelido(String jmfApelido) {
        this.jmfApelido = jmfApelido;
    }

    
    @Column(name="jmf_cpf", length=14)
    public String getJmfCpf() {
        return this.jmfCpf;
    }
    
    public void setJmfCpf(String jmfCpf) {
        this.jmfCpf = jmfCpf;
    }

    
    @Column(name="jmf_rg", length=12)
    public String getJmfRg() {
        return this.jmfRg;
    }
    
    public void setJmfRg(String jmfRg) {
        this.jmfRg = jmfRg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jmf_data_nascimento", length=10)
    public Date getJmfDataNascimento() {
        return this.jmfDataNascimento;
    }
    
    public void setJmfDataNascimento(Date jmfDataNascimento) {
        this.jmfDataNascimento = jmfDataNascimento;
    }

    
    @Column(name="jmf_celular", length=15)
    public String getJmfCelular() {
        return this.jmfCelular;
    }
    
    public void setJmfCelular(String jmfCelular) {
        this.jmfCelular = jmfCelular;
    }

    
    @Column(name="jmf_email", length=100)
    public String getJmfEmail() {
        return this.jmfEmail;
    }
    
    public void setJmfEmail(String jmfEmail) {
        this.jmfEmail = jmfEmail;
    }

    
    @Column(name="jmf_endereco", length=100)
    public String getJmfEndereco() {
        return this.jmfEndereco;
    }
    
    public void setJmfEndereco(String jmfEndereco) {
        this.jmfEndereco = jmfEndereco;
    }

    
    @Column(name="jmf_cidade", length=50)
    public String getJmfCidade() {
        return this.jmfCidade;
    }
    
    public void setJmfCidade(String jmfCidade) {
        this.jmfCidade = jmfCidade;
    }

    
    @Column(name="jmf_estado", length=2)
    public String getJmfEstado() {
        return this.jmfEstado;
    }
    
    public void setJmfEstado(String jmfEstado) {
        this.jmfEstado = jmfEstado;
    }

    
    @Column(name="jmf_ativo", length=1)
    public String getJmfAtivo() {
        return this.jmfAtivo;
    }
    
    public void setJmfAtivo(String jmfAtivo) {
        this.jmfAtivo = jmfAtivo;
    }




}


